#!/bin/bash



declare -a filenames=( 103-the_biggest_fan 102-acrostic 101-gifs 100-empty_casks )




#creating the files

for filename in ${filenames[@]}

do

echo \#\!/bin/bash >> $filename

chmod u+x $filename

done




echo "tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d ' ' -f -1 | rev" >> 103-the_biggest_fan

echo "echo $(cut -c 1 | tr -d "\n")" >> 102-acrostic

echo "find -name '*.gif' -type f -printf '%f\n' |  LC_ALL=C sort -f | rev | cut -c 5- | rev" >> 101-gifs

echo "find . -empty | rev | cut -d '/' -f 1 | rev" >> 100-empty_casks






# Un-comment this if you want to commit the changes and push to your git repositor

#git add .

#git commit -m "commit using script"

#git push
