#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine- Install nginx
sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
