#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine- Install nginx
apt -y update
apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
# Configure your Nginx server so that /redirect_me is redirecting to another page.
echo "server {
        location /redirect_me {
                return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" >> /etc/nginx/nginx.conf

service nginx start
