#!/usr/bin/env bash
# install load balancer
sudo apt update
sudo apt install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo echo -e "\nfrontend http-in" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 111191-web-01 54.90.3.149:80 check" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 111191-web-02 75.101.217.125:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

