#!/usr/bin/env bash
# Nginx must be running, and listening on port
# 80 of all the server’s active IPv4 IPs
link="/etc/nginx/sites-enabled/default"
target="/etc/nginx/sites-available/default"
sudo rm $link
sudo ln -s $target $link
sudo service nginx restart
