#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
apt-get -y update
apt-get -y install nginx
sudo sed -i '/listen 80;/a listen [::]:80;' /etc/nginx/sites-available/default
service nginx restart
