#!/usr/bin/env bash
# Get the process IDs of the Gunicorn workers
worker_pids=$(pgrep gunicorn)

# Reload Gunicorn by sending a SIGHUP signal to each worker
for pid in $worker_pids; do
    kill -s HUP "$pid"
done
